export const AUTHENTICATED_ROUTES = {
  market: "/",
  wallet:"/wallet",
  setting:"/setting",
  event:"/event",
  orders:"/orders",
  event_details:"/event-details",


  guest_management: "/guest-management",
  event_management: "/event-management",
  event_management_details: "/event-management/details",
  notifications: "/notifications",
  profile: "/profile",
  signin: "/login",
  signup: "/register",
  settings: "/settings",
  event_management_aso_ebi: "/event-management/aso-ebi",
  invitation: "/event-management/invite",
  etag: "/event-management/etag",
  aso_ebi_guest: "/aso-ebi/guest",
  floor_plan: "/event-management/floorplan",
  vendor_management: "/event-management/vendor",
  spraya: "spraya",
  checklist: "/event-management/checklist",
  // checklist: "/event-management/checklist",
};
